#pragma once

#include "NativeGameplayTags.h"

namespace PurgatoriumLexGameplayTags
{
	PURGATORIUMLEX_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Input Tags - These are used to bind InputActions to Gameplay Abilities via Input ID
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChargeAttack);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialAttack);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Guard);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dodge);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Run);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Posture);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LockUnlock);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_BreakGuard);
}

