#pragma once

#include "NativeGameplayTags.h"

namespace PurgatoriumLexGameplayTags
{
	PURGATORIUMLEX_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Input Tags - These are used to bind InputActions to Gameplay Abilities via Input ID
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChargeAttack);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialAttack);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Guard);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Parry);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Run);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Posture);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LockUnlock);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_BreakGuard);

	// --------------------------------------------------------------------
	// State System Tags - Use as authoritative character state (no bools)
	// --------------------------------------------------------------------
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Grounded);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Airborne);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hitstun);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Blocking);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Rolling);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_PostureChanging);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Grabbing);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_KnockedDown);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invulnerable);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_SuperArmor);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Parrying);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Parried);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_CounterHit);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stunned);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Jumping);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_WallSplat);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_GroundBounce);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_GettingUp);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Tech);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_BeingGrabbed);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_GrabBreak);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Taunting);
	PURGATORIUMLEX_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
}

