;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Abilities.Conditions.Silenced",DevComment="")
+GameplayTagList=(Tag="Abilities.Conditions.Stunned",DevComment="")
+GameplayTagList=(Tag="Damage.Conditions.Immune",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Kick",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Kick",DevComment="")
+GameplayTagList=(Tag="Gameplay.Cooldown.Kick",DevComment="")
+GameplayTagList=(Tag="Gameplay.Magnitude.Duration",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.IsKicking",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Kick",DevComment="")
+GameplayTagList=(Tag="InputTag.LightAttack",DevComment="Light Attack input tag for abilities.")
+GameplayTagList=(Tag="InputTag.ChargeAttack",DevComment="Charge Attack input tag for abilities.")
+GameplayTagList=(Tag="InputTag.SpecialAttack",DevComment="Special Attack input tag for abilities.")
+GameplayTagList=(Tag="InputTag.Guard",DevComment="Guard input tag for abilities.")
+GameplayTagList=(Tag="InputTag.Parry",DevComment="Parry input tag for abilities (triggered on Guard release).")
+GameplayTagList=(Tag="InputTag.Roll",DevComment="Roll input tag for abilities.")
+GameplayTagList=(Tag="InputTag.Jump",DevComment="Jump input tag.")
+GameplayTagList=(Tag="InputTag.Move",DevComment="Move input tag.")
+GameplayTagList=(Tag="InputTag.Look",DevComment="Look input tag.")
+GameplayTagList=(Tag="InputTag.Run",DevComment="Run input tag.")
+GameplayTagList=(Tag="InputTag.Posture",DevComment="Posture input tag.")
+GameplayTagList=(Tag="InputTag.LockUnlock",DevComment="Lock/Unlock camera input tag.")
+GameplayTagList=(Tag="InputTag.BreakGuard",DevComment="Break Guard input tag for abilities.")

